deepc_node:
  ros__parameters:
    use_sim_time: true

    cmd_topic: /cmd_vel
    odom_topic: /model/rosbot/odometry_gt
    path_topic: /deepc/reference_path

    sample_time: 0.05

    reference_csv: /ws/ref/test_reference.csv
    append_final_stop_steps: 20

    goal_pos_tol: 0.08
    goal_yaw_tol: 0.15
    final_hold_steps: 10
    max_final_stop_steps: 200

    kx: 0.8
    ky: 1.8
    kpsi: 2.0

    v_min: -0.2
    v_max: 0.45
    w_min: -1.2
    w_max: 1.2

    dataset_mode: mosaic
    dataset_dir: /ws/datasets/mosaic
    dataset_csv: ""
    dataset_glob: "*.csv"
    drop_initial_rows: 20
    min_rows_per_dataset: 80

    Tini: 15
    horizon: 10
    Q_diag: [10.0, 10.0, 30.0] # Output cost coefficient, [e_x, e_y, e_psi]
    R_diag: [1.0, 0.5] # Input cost coeficient, [v, w]
    lambda_g: 1.0
    lambda_y: 10000.0
    solver_name: OSQP

    ref_back_search: 3
    ref_forward_search: 25

    goal_pos_tol: 0.08
    goal_yaw_tol: 0.15
    final_hold_steps: 10
    max_final_stop_steps: 200